<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Tests\Controllers;

use SquareConnectAPILib\Controllers\CustomerSegmentsController;
use SquareConnectAPILib\Exceptions;

class CustomerSegmentsControllerTest extends BaseTestController
{
    /**
     * @var CustomerSegmentsController CustomerSegmentsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getCustomerSegmentsController();
    }

    public function testListCustomerSegments()
    {
        // Parameters for the API call
        $cursor = null;
        $limit = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listCustomerSegments($cursor, $limit);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
