<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Tests\Controllers;

use SquareConnectAPILib\Controllers\LaborController;
use SquareConnectAPILib\Exceptions;

class LaborControllerTest extends BaseTestController
{
    /**
     * @var LaborController LaborController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getLaborController();
    }

    public function testListBreakTypes()
    {
        // Parameters for the API call
        $locationId = null;
        $limit = null;
        $cursor = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listBreakTypes($locationId, $limit, $cursor);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testListEmployeeWages()
    {
        // Parameters for the API call
        $employeeId = null;
        $limit = null;
        $cursor = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listEmployeeWages($employeeId, $limit, $cursor);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testListTeamMemberWages()
    {
        // Parameters for the API call
        $teamMemberId = null;
        $limit = null;
        $cursor = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listTeamMemberWages($teamMemberId, $limit, $cursor);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testListWorkweekConfigs()
    {
        // Parameters for the API call
        $limit = null;
        $cursor = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listWorkweekConfigs($limit, $cursor);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
