<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Tests\Controllers;

use SquareConnectAPILib\Controllers\PaymentsController;
use SquareConnectAPILib\Exceptions;

class PaymentsControllerTest extends BaseTestController
{
    /**
     * @var PaymentsController PaymentsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getPaymentsController();
    }

    public function testListPayments()
    {
        // Parameters for the API call
        $beginTime = null;
        $endTime = null;
        $sortOrder = null;
        $cursor = null;
        $locationId = null;
        $total = null;
        $last4 = null;
        $cardBrand = null;
        $limit = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listPayments(
                $beginTime,
                $endTime,
                $sortOrder,
                $cursor,
                $locationId,
                $total,
                $last4,
                $cardBrand,
                $limit
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
