<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Tests;

use Core\Types\CallbackCatcher;
use SquareConnectAPILib\Authentication\Oauth2ClientSecretCredentialsBuilder;
use SquareConnectAPILib\Authentication\Oauth2CredentialsBuilder;
use SquareConnectAPILib\SquareConnectAPIClient;
use SquareConnectAPILib\SquareConnectAPIClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): SquareConnectAPIClient
    {
        $clientBuilder = SquareConnectAPIClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(SquareConnectAPIClientBuilder $builder): SquareConnectAPIClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        SquareConnectAPIClientBuilder $builder
    ): SquareConnectAPIClientBuilder {
        $timeout = getenv('SQUARE_CONNECT_API_LIB_TIMEOUT');
        $numberOfRetries = getenv('SQUARE_CONNECT_API_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('SQUARE_CONNECT_API_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('SQUARE_CONNECT_API_LIB_ENVIRONMENT');
        $oAuthClientId = getenv('SQUARE_CONNECT_API_LIB_O_AUTH_CLIENT_ID');
        $oAuthClientSecret = getenv('SQUARE_CONNECT_API_LIB_O_AUTH_CLIENT_SECRET');
        $oAuthRedirectUri = getenv('SQUARE_CONNECT_API_LIB_O_AUTH_REDIRECT_URI');
        $authorization = getenv('SQUARE_CONNECT_API_LIB_AUTHORIZATION');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($oAuthClientId) && !empty($oAuthClientSecret) && !empty($oAuthRedirectUri)) {
            $builder->oauth2Credentials(
                Oauth2CredentialsBuilder::init($oAuthClientId, $oAuthClientSecret, $oAuthRedirectUri)
            );
        }

        if (!empty($authorization)) {
            $builder->oauth2ClientSecretCredentials(Oauth2ClientSecretCredentialsBuilder::init($authorization));
        }

        return $builder;
    }
}
