<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\AdjustLoyaltyPointsRequest;
use SquareConnectAPILib\Models\LoyaltyEventAdjustPoints;

/**
 * Builder for model AdjustLoyaltyPointsRequest
 *
 * @see AdjustLoyaltyPointsRequest
 */
class AdjustLoyaltyPointsRequestBuilder
{
    /**
     * @var AdjustLoyaltyPointsRequest
     */
    private $instance;

    private function __construct(AdjustLoyaltyPointsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Adjust Loyalty Points Request Builder object.
     *
     * @param LoyaltyEventAdjustPoints $adjustPoints
     * @param string $idempotencyKey
     */
    public static function init(LoyaltyEventAdjustPoints $adjustPoints, string $idempotencyKey): self
    {
        return new self(new AdjustLoyaltyPointsRequest($adjustPoints, $idempotencyKey));
    }

    /**
     * Initializes a new Adjust Loyalty Points Request object.
     */
    public function build(): AdjustLoyaltyPointsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
