<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\BatchDeleteCatalogObjectsRequest;

/**
 * Builder for model BatchDeleteCatalogObjectsRequest
 *
 * @see BatchDeleteCatalogObjectsRequest
 */
class BatchDeleteCatalogObjectsRequestBuilder
{
    /**
     * @var BatchDeleteCatalogObjectsRequest
     */
    private $instance;

    private function __construct(BatchDeleteCatalogObjectsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Batch Delete Catalog Objects Request Builder object.
     */
    public static function init(): self
    {
        return new self(new BatchDeleteCatalogObjectsRequest());
    }

    /**
     * Sets object ids field.
     *
     * @param string[]|null $value
     */
    public function objectIds(?array $value): self
    {
        $this->instance->setObjectIds($value);
        return $this;
    }

    /**
     * Initializes a new Batch Delete Catalog Objects Request object.
     */
    public function build(): BatchDeleteCatalogObjectsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
