<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\BatchRetrieveInventoryCountsRequest;

/**
 * Builder for model BatchRetrieveInventoryCountsRequest
 *
 * @see BatchRetrieveInventoryCountsRequest
 */
class BatchRetrieveInventoryCountsRequestBuilder
{
    /**
     * @var BatchRetrieveInventoryCountsRequest
     */
    private $instance;

    private function __construct(BatchRetrieveInventoryCountsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Batch Retrieve Inventory Counts Request Builder object.
     */
    public static function init(): self
    {
        return new self(new BatchRetrieveInventoryCountsRequest());
    }

    /**
     * Sets catalog object ids field.
     *
     * @param string[]|null $value
     */
    public function catalogObjectIds(?array $value): self
    {
        $this->instance->setCatalogObjectIds($value);
        return $this;
    }

    /**
     * Sets cursor field.
     *
     * @param string|null $value
     */
    public function cursor(?string $value): self
    {
        $this->instance->setCursor($value);
        return $this;
    }

    /**
     * Sets location ids field.
     *
     * @param string[]|null $value
     */
    public function locationIds(?array $value): self
    {
        $this->instance->setLocationIds($value);
        return $this;
    }

    /**
     * Sets states field.
     *
     * @param string[]|null $value
     */
    public function states(?array $value): self
    {
        $this->instance->setStates($value);
        return $this;
    }

    /**
     * Sets updated after field.
     *
     * @param string|null $value
     */
    public function updatedAfter(?string $value): self
    {
        $this->instance->setUpdatedAfter($value);
        return $this;
    }

    /**
     * Initializes a new Batch Retrieve Inventory Counts Request object.
     */
    public function build(): BatchRetrieveInventoryCountsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
