<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CancelBookingRequest;

/**
 * Builder for model CancelBookingRequest
 *
 * @see CancelBookingRequest
 */
class CancelBookingRequestBuilder
{
    /**
     * @var CancelBookingRequest
     */
    private $instance;

    private function __construct(CancelBookingRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cancel Booking Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CancelBookingRequest());
    }

    /**
     * Sets booking version field.
     *
     * @param int|null $value
     */
    public function bookingVersion(?int $value): self
    {
        $this->instance->setBookingVersion($value);
        return $this;
    }

    /**
     * Sets idempotency key field.
     *
     * @param string|null $value
     */
    public function idempotencyKey(?string $value): self
    {
        $this->instance->setIdempotencyKey($value);
        return $this;
    }

    /**
     * Initializes a new Cancel Booking Request object.
     */
    public function build(): CancelBookingRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
