<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CatalogProductSet;

/**
 * Builder for model CatalogProductSet
 *
 * @see CatalogProductSet
 */
class CatalogProductSetBuilder
{
    /**
     * @var CatalogProductSet
     */
    private $instance;

    private function __construct(CatalogProductSet $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Catalog Product Set Builder object.
     */
    public static function init(): self
    {
        return new self(new CatalogProductSet());
    }

    /**
     * Sets all products field.
     *
     * @param bool|null $value
     */
    public function allProducts(?bool $value): self
    {
        $this->instance->setAllProducts($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets product ids all field.
     *
     * @param string[]|null $value
     */
    public function productIdsAll(?array $value): self
    {
        $this->instance->setProductIdsAll($value);
        return $this;
    }

    /**
     * Sets product ids any field.
     *
     * @param string[]|null $value
     */
    public function productIdsAny(?array $value): self
    {
        $this->instance->setProductIdsAny($value);
        return $this;
    }

    /**
     * Sets quantity exact field.
     *
     * @param int|null $value
     */
    public function quantityExact(?int $value): self
    {
        $this->instance->setQuantityExact($value);
        return $this;
    }

    /**
     * Sets quantity max field.
     *
     * @param int|null $value
     */
    public function quantityMax(?int $value): self
    {
        $this->instance->setQuantityMax($value);
        return $this;
    }

    /**
     * Sets quantity min field.
     *
     * @param int|null $value
     */
    public function quantityMin(?int $value): self
    {
        $this->instance->setQuantityMin($value);
        return $this;
    }

    /**
     * Initializes a new Catalog Product Set object.
     */
    public function build(): CatalogProductSet
    {
        return CoreHelper::clone($this->instance);
    }
}
