<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CatalogCustomAttributeDefinition;
use SquareConnectAPILib\Models\CatalogCustomAttributeDefinitionNumberConfig;
use SquareConnectAPILib\Models\CatalogCustomAttributeDefinitionSelectionConfig;
use SquareConnectAPILib\Models\CatalogCustomAttributeDefinitionStringConfig;
use SquareConnectAPILib\Models\SourceApplication;

/**
 * Builder for model CatalogCustomAttributeDefinition
 *
 * @see CatalogCustomAttributeDefinition
 */
class CatalogCustomAttributeDefinitionBuilder
{
    /**
     * @var CatalogCustomAttributeDefinition
     */
    private $instance;

    private function __construct(CatalogCustomAttributeDefinition $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Catalog Custom Attribute Definition Builder object.
     *
     * @param string[] $allowedObjectTypes
     * @param string $name
     * @param string $type
     */
    public static function init(array $allowedObjectTypes, string $name, string $type): self
    {
        return new self(new CatalogCustomAttributeDefinition($allowedObjectTypes, $name, $type));
    }

    /**
     * Sets app visibility field.
     *
     * @param string|null $value
     */
    public function appVisibility(?string $value): self
    {
        $this->instance->setAppVisibility($value);
        return $this;
    }

    /**
     * Sets custom attribute usage count field.
     *
     * @param int|null $value
     */
    public function customAttributeUsageCount(?int $value): self
    {
        $this->instance->setCustomAttributeUsageCount($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets key field.
     *
     * @param string|null $value
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets number config field.
     *
     * @param CatalogCustomAttributeDefinitionNumberConfig|null $value
     */
    public function numberConfig(?CatalogCustomAttributeDefinitionNumberConfig $value): self
    {
        $this->instance->setNumberConfig($value);
        return $this;
    }

    /**
     * Sets selection config field.
     *
     * @param CatalogCustomAttributeDefinitionSelectionConfig|null $value
     */
    public function selectionConfig(?CatalogCustomAttributeDefinitionSelectionConfig $value): self
    {
        $this->instance->setSelectionConfig($value);
        return $this;
    }

    /**
     * Sets seller visibility field.
     *
     * @param string|null $value
     */
    public function sellerVisibility(?string $value): self
    {
        $this->instance->setSellerVisibility($value);
        return $this;
    }

    /**
     * Sets source application field.
     *
     * @param SourceApplication|null $value
     */
    public function sourceApplication(?SourceApplication $value): self
    {
        $this->instance->setSourceApplication($value);
        return $this;
    }

    /**
     * Sets string config field.
     *
     * @param CatalogCustomAttributeDefinitionStringConfig|null $value
     */
    public function stringConfig(?CatalogCustomAttributeDefinitionStringConfig $value): self
    {
        $this->instance->setStringConfig($value);
        return $this;
    }

    /**
     * Initializes a new Catalog Custom Attribute Definition object.
     */
    public function build(): CatalogCustomAttributeDefinition
    {
        return CoreHelper::clone($this->instance);
    }
}
