<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CatalogStockConversion;

/**
 * Builder for model CatalogStockConversion
 *
 * @see CatalogStockConversion
 */
class CatalogStockConversionBuilder
{
    /**
     * @var CatalogStockConversion
     */
    private $instance;

    private function __construct(CatalogStockConversion $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Catalog Stock Conversion Builder object.
     *
     * @param string $nonstockableQuantity
     * @param string $stockableItemVariationId
     * @param string $stockableQuantity
     */
    public static function init(
        string $nonstockableQuantity,
        string $stockableItemVariationId,
        string $stockableQuantity
    ): self {
        return new self(
            new CatalogStockConversion($nonstockableQuantity, $stockableItemVariationId, $stockableQuantity)
        );
    }

    /**
     * Initializes a new Catalog Stock Conversion object.
     */
    public function build(): CatalogStockConversion
    {
        return CoreHelper::clone($this->instance);
    }
}
