<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CatalogItemModifierListInfo;
use SquareConnectAPILib\Models\CatalogModifierOverride;

/**
 * Builder for model CatalogItemModifierListInfo
 *
 * @see CatalogItemModifierListInfo
 */
class CatalogItemModifierListInfoBuilder
{
    /**
     * @var CatalogItemModifierListInfo
     */
    private $instance;

    private function __construct(CatalogItemModifierListInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Catalog Item Modifier List Info Builder object.
     *
     * @param string $modifierListId
     */
    public static function init(string $modifierListId): self
    {
        return new self(new CatalogItemModifierListInfo($modifierListId));
    }

    /**
     * Sets enabled field.
     *
     * @param bool|null $value
     */
    public function enabled(?bool $value): self
    {
        $this->instance->setEnabled($value);
        return $this;
    }

    /**
     * Sets max selected modifiers field.
     *
     * @param int|null $value
     */
    public function maxSelectedModifiers(?int $value): self
    {
        $this->instance->setMaxSelectedModifiers($value);
        return $this;
    }

    /**
     * Sets min selected modifiers field.
     *
     * @param int|null $value
     */
    public function minSelectedModifiers(?int $value): self
    {
        $this->instance->setMinSelectedModifiers($value);
        return $this;
    }

    /**
     * Sets modifier overrides field.
     *
     * @param CatalogModifierOverride[]|null $value
     */
    public function modifierOverrides(?array $value): self
    {
        $this->instance->setModifierOverrides($value);
        return $this;
    }

    /**
     * Initializes a new Catalog Item Modifier List Info object.
     */
    public function build(): CatalogItemModifierListInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
