<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CatalogImage;

/**
 * Builder for model CatalogImage
 *
 * @see CatalogImage
 */
class CatalogImageBuilder
{
    /**
     * @var CatalogImage
     */
    private $instance;

    private function __construct(CatalogImage $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Catalog Image Builder object.
     */
    public static function init(): self
    {
        return new self(new CatalogImage());
    }

    /**
     * Sets caption field.
     *
     * @param string|null $value
     */
    public function caption(?string $value): self
    {
        $this->instance->setCaption($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Initializes a new Catalog Image object.
     */
    public function build(): CatalogImage
    {
        return CoreHelper::clone($this->instance);
    }
}
