<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CatalogQueryRange;

/**
 * Builder for model CatalogQueryRange
 *
 * @see CatalogQueryRange
 */
class CatalogQueryRangeBuilder
{
    /**
     * @var CatalogQueryRange
     */
    private $instance;

    private function __construct(CatalogQueryRange $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Catalog Query Range Builder object.
     *
     * @param string $attributeName
     */
    public static function init(string $attributeName): self
    {
        return new self(new CatalogQueryRange($attributeName));
    }

    /**
     * Sets attribute max value field.
     *
     * @param int|null $value
     */
    public function attributeMaxValue(?int $value): self
    {
        $this->instance->setAttributeMaxValue($value);
        return $this;
    }

    /**
     * Sets attribute min value field.
     *
     * @param int|null $value
     */
    public function attributeMinValue(?int $value): self
    {
        $this->instance->setAttributeMinValue($value);
        return $this;
    }

    /**
     * Initializes a new Catalog Query Range object.
     */
    public function build(): CatalogQueryRange
    {
        return CoreHelper::clone($this->instance);
    }
}
