<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CatalogItemOptionValueForItemVariation;
use SquareConnectAPILib\Models\CatalogItemVariation;
use SquareConnectAPILib\Models\CatalogStockConversion;
use SquareConnectAPILib\Models\ItemVariationLocationOverrides;
use SquareConnectAPILib\Models\Money;

/**
 * Builder for model CatalogItemVariation
 *
 * @see CatalogItemVariation
 */
class CatalogItemVariationBuilder
{
    /**
     * @var CatalogItemVariation
     */
    private $instance;

    private function __construct(CatalogItemVariation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Catalog Item Variation Builder object.
     */
    public static function init(): self
    {
        return new self(new CatalogItemVariation());
    }

    /**
     * Sets available for booking field.
     *
     * @param bool|null $value
     */
    public function availableForBooking(?bool $value): self
    {
        $this->instance->setAvailableForBooking($value);
        return $this;
    }

    /**
     * Sets inventory alert threshold field.
     *
     * @param int|null $value
     */
    public function inventoryAlertThreshold(?int $value): self
    {
        $this->instance->setInventoryAlertThreshold($value);
        return $this;
    }

    /**
     * Sets inventory alert type field.
     *
     * @param string|null $value
     */
    public function inventoryAlertType(?string $value): self
    {
        $this->instance->setInventoryAlertType($value);
        return $this;
    }

    /**
     * Sets item id field.
     *
     * @param string|null $value
     */
    public function itemId(?string $value): self
    {
        $this->instance->setItemId($value);
        return $this;
    }

    /**
     * Sets item option values field.
     *
     * @param CatalogItemOptionValueForItemVariation[]|null $value
     */
    public function itemOptionValues(?array $value): self
    {
        $this->instance->setItemOptionValues($value);
        return $this;
    }

    /**
     * Sets location overrides field.
     *
     * @param ItemVariationLocationOverrides[]|null $value
     */
    public function locationOverrides(?array $value): self
    {
        $this->instance->setLocationOverrides($value);
        return $this;
    }

    /**
     * Sets measurement unit id field.
     *
     * @param string|null $value
     */
    public function measurementUnitId(?string $value): self
    {
        $this->instance->setMeasurementUnitId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets ordinal field.
     *
     * @param int|null $value
     */
    public function ordinal(?int $value): self
    {
        $this->instance->setOrdinal($value);
        return $this;
    }

    /**
     * Sets price money field.
     *
     * @param Money|null $value
     */
    public function priceMoney(?Money $value): self
    {
        $this->instance->setPriceMoney($value);
        return $this;
    }

    /**
     * Sets pricing type field.
     *
     * @param string|null $value
     */
    public function pricingType(?string $value): self
    {
        $this->instance->setPricingType($value);
        return $this;
    }

    /**
     * Sets service duration field.
     *
     * @param int|null $value
     */
    public function serviceDuration(?int $value): self
    {
        $this->instance->setServiceDuration($value);
        return $this;
    }

    /**
     * Sets sku field.
     *
     * @param string|null $value
     */
    public function sku(?string $value): self
    {
        $this->instance->setSku($value);
        return $this;
    }

    /**
     * Sets stockable field.
     *
     * @param bool|null $value
     */
    public function stockable(?bool $value): self
    {
        $this->instance->setStockable($value);
        return $this;
    }

    /**
     * Sets stockable conversion field.
     *
     * @param CatalogStockConversion|null $value
     */
    public function stockableConversion(?CatalogStockConversion $value): self
    {
        $this->instance->setStockableConversion($value);
        return $this;
    }

    /**
     * Sets team member ids field.
     *
     * @param string[]|null $value
     */
    public function teamMemberIds(?array $value): self
    {
        $this->instance->setTeamMemberIds($value);
        return $this;
    }

    /**
     * Sets track inventory field.
     *
     * @param bool|null $value
     */
    public function trackInventory(?bool $value): self
    {
        $this->instance->setTrackInventory($value);
        return $this;
    }

    /**
     * Sets upc field.
     *
     * @param string|null $value
     */
    public function upc(?string $value): self
    {
        $this->instance->setUpc($value);
        return $this;
    }

    /**
     * Sets user data field.
     *
     * @param string|null $value
     */
    public function userData(?string $value): self
    {
        $this->instance->setUserData($value);
        return $this;
    }

    /**
     * Initializes a new Catalog Item Variation object.
     */
    public function build(): CatalogItemVariation
    {
        return CoreHelper::clone($this->instance);
    }
}
