<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CreateInvoiceResponse;
use SquareConnectAPILib\Models\Error;
use SquareConnectAPILib\Models\Invoice;

/**
 * Builder for model CreateInvoiceResponse
 *
 * @see CreateInvoiceResponse
 */
class CreateInvoiceResponseBuilder
{
    /**
     * @var CreateInvoiceResponse
     */
    private $instance;

    private function __construct(CreateInvoiceResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Invoice Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateInvoiceResponse());
    }

    /**
     * Sets errors field.
     *
     * @param Error[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Sets invoice field.
     *
     * @param Invoice|null $value
     */
    public function invoice(?Invoice $value): self
    {
        $this->instance->setInvoice($value);
        return $this;
    }

    /**
     * Initializes a new Create Invoice Response object.
     */
    public function build(): CreateInvoiceResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
