<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\CreateGiftCardRequest;
use SquareConnectAPILib\Models\GiftCard;

/**
 * Builder for model CreateGiftCardRequest
 *
 * @see CreateGiftCardRequest
 */
class CreateGiftCardRequestBuilder
{
    /**
     * @var CreateGiftCardRequest
     */
    private $instance;

    private function __construct(CreateGiftCardRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Gift Card Request Builder object.
     *
     * @param GiftCard $giftCard
     * @param string $idempotencyKey
     * @param string $locationId
     */
    public static function init(GiftCard $giftCard, string $idempotencyKey, string $locationId): self
    {
        return new self(new CreateGiftCardRequest($giftCard, $idempotencyKey, $locationId));
    }

    /**
     * Initializes a new Create Gift Card Request object.
     */
    public function build(): CreateGiftCardRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
