<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\DeleteBreakTypeResponse;
use SquareConnectAPILib\Models\Error;

/**
 * Builder for model DeleteBreakTypeResponse
 *
 * @see DeleteBreakTypeResponse
 */
class DeleteBreakTypeResponseBuilder
{
    /**
     * @var DeleteBreakTypeResponse
     */
    private $instance;

    private function __construct(DeleteBreakTypeResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Delete Break Type Response Builder object.
     */
    public static function init(): self
    {
        return new self(new DeleteBreakTypeResponse());
    }

    /**
     * Sets errors field.
     *
     * @param Error[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Delete Break Type Response object.
     */
    public function build(): DeleteBreakTypeResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
