<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\DeviceCheckoutOptions;
use SquareConnectAPILib\Models\TipSettings;

/**
 * Builder for model DeviceCheckoutOptions
 *
 * @see DeviceCheckoutOptions
 */
class DeviceCheckoutOptionsBuilder
{
    /**
     * @var DeviceCheckoutOptions
     */
    private $instance;

    private function __construct(DeviceCheckoutOptions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Checkout Options Builder object.
     *
     * @param string $deviceId
     */
    public static function init(string $deviceId): self
    {
        return new self(new DeviceCheckoutOptions($deviceId));
    }

    /**
     * Sets skip receipt screen field.
     *
     * @param bool|null $value
     */
    public function skipReceiptScreen(?bool $value): self
    {
        $this->instance->setSkipReceiptScreen($value);
        return $this;
    }

    /**
     * Sets tip settings field.
     *
     * @param TipSettings|null $value
     */
    public function tipSettings(?TipSettings $value): self
    {
        $this->instance->setTipSettings($value);
        return $this;
    }

    /**
     * Initializes a new Device Checkout Options object.
     */
    public function build(): DeviceCheckoutOptions
    {
        return CoreHelper::clone($this->instance);
    }
}
