<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\Device;

/**
 * Builder for model Device
 *
 * @see Device
 */
class DeviceBuilder
{
    /**
     * @var Device
     */
    private $instance;

    private function __construct(Device $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Builder object.
     */
    public static function init(): self
    {
        return new self(new Device());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Device object.
     */
    public function build(): Device
    {
        return CoreHelper::clone($this->instance);
    }
}
