<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\DigitalWalletDetails;

/**
 * Builder for model DigitalWalletDetails
 *
 * @see DigitalWalletDetails
 */
class DigitalWalletDetailsBuilder
{
    /**
     * @var DigitalWalletDetails
     */
    private $instance;

    private function __construct(DigitalWalletDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Digital Wallet Details Builder object.
     */
    public static function init(): self
    {
        return new self(new DigitalWalletDetails());
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Digital Wallet Details object.
     */
    public function build(): DigitalWalletDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
