<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\Dispute;
use SquareConnectAPILib\Models\DisputeEvidenceCreatedWebhookObject;

/**
 * Builder for model DisputeEvidenceCreatedWebhookObject
 *
 * @see DisputeEvidenceCreatedWebhookObject
 */
class DisputeEvidenceCreatedWebhookObjectBuilder
{
    /**
     * @var DisputeEvidenceCreatedWebhookObject
     */
    private $instance;

    private function __construct(DisputeEvidenceCreatedWebhookObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Dispute Evidence Created Webhook Object Builder object.
     */
    public static function init(): self
    {
        return new self(new DisputeEvidenceCreatedWebhookObject());
    }

    /**
     * Sets object field.
     *
     * @param Dispute|null $value
     */
    public function object(?Dispute $value): self
    {
        $this->instance->setObject($value);
        return $this;
    }

    /**
     * Initializes a new Dispute Evidence Created Webhook Object object.
     */
    public function build(): DisputeEvidenceCreatedWebhookObject
    {
        return CoreHelper::clone($this->instance);
    }
}
