<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\FilterValue;

/**
 * Builder for model FilterValue
 *
 * @see FilterValue
 */
class FilterValueBuilder
{
    /**
     * @var FilterValue
     */
    private $instance;

    private function __construct(FilterValue $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Filter Value Builder object.
     */
    public static function init(): self
    {
        return new self(new FilterValue());
    }

    /**
     * Sets all field.
     *
     * @param string[]|null $value
     */
    public function all(?array $value): self
    {
        $this->instance->setAll($value);
        return $this;
    }

    /**
     * Sets any field.
     *
     * @param string[]|null $value
     */
    public function any(?array $value): self
    {
        $this->instance->setAny($value);
        return $this;
    }

    /**
     * Sets none field.
     *
     * @param string[]|null $value
     */
    public function none(?array $value): self
    {
        $this->instance->setNone($value);
        return $this;
    }

    /**
     * Initializes a new Filter Value object.
     */
    public function build(): FilterValue
    {
        return CoreHelper::clone($this->instance);
    }
}
