<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\Error;
use SquareConnectAPILib\Models\GetShiftResponse;
use SquareConnectAPILib\Models\Shift;

/**
 * Builder for model GetShiftResponse
 *
 * @see GetShiftResponse
 */
class GetShiftResponseBuilder
{
    /**
     * @var GetShiftResponse
     */
    private $instance;

    private function __construct(GetShiftResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Shift Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetShiftResponse());
    }

    /**
     * Sets errors field.
     *
     * @param Error[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Sets shift field.
     *
     * @param Shift|null $value
     */
    public function shift(?Shift $value): self
    {
        $this->instance->setShift($value);
        return $this;
    }

    /**
     * Initializes a new Get Shift Response object.
     */
    public function build(): GetShiftResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
