<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\GiftCardActivityAdjustDecrement;
use SquareConnectAPILib\Models\Money;

/**
 * Builder for model GiftCardActivityAdjustDecrement
 *
 * @see GiftCardActivityAdjustDecrement
 */
class GiftCardActivityAdjustDecrementBuilder
{
    /**
     * @var GiftCardActivityAdjustDecrement
     */
    private $instance;

    private function __construct(GiftCardActivityAdjustDecrement $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Gift Card Activity Adjust Decrement Builder object.
     *
     * @param Money $amountMoney
     * @param array $reason
     */
    public static function init(Money $amountMoney, array $reason): self
    {
        return new self(new GiftCardActivityAdjustDecrement($amountMoney, $reason));
    }

    /**
     * Initializes a new Gift Card Activity Adjust Decrement object.
     */
    public function build(): GiftCardActivityAdjustDecrement
    {
        return CoreHelper::clone($this->instance);
    }
}
