<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\GiftCardActivityDeactivate;

/**
 * Builder for model GiftCardActivityDeactivate
 *
 * @see GiftCardActivityDeactivate
 */
class GiftCardActivityDeactivateBuilder
{
    /**
     * @var GiftCardActivityDeactivate
     */
    private $instance;

    private function __construct(GiftCardActivityDeactivate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Gift Card Activity Deactivate Builder object.
     *
     * @param array $reason
     */
    public static function init(array $reason): self
    {
        return new self(new GiftCardActivityDeactivate($reason));
    }

    /**
     * Initializes a new Gift Card Activity Deactivate object.
     */
    public function build(): GiftCardActivityDeactivate
    {
        return CoreHelper::clone($this->instance);
    }
}
