<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\MBreak;

/**
 * Builder for model MBreak
 *
 * @see MBreak
 */
class MBreakBuilder
{
    /**
     * @var MBreak
     */
    private $instance;

    private function __construct(MBreak $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new M Break Builder object.
     *
     * @param string $breakTypeId
     * @param string $expectedDuration
     * @param bool $isPaid
     * @param string $name
     * @param string $startAt
     */
    public static function init(
        string $breakTypeId,
        string $expectedDuration,
        bool $isPaid,
        string $name,
        string $startAt
    ): self {
        return new self(new MBreak($breakTypeId, $expectedDuration, $isPaid, $name, $startAt));
    }

    /**
     * Sets end at field.
     *
     * @param string|null $value
     */
    public function endAt(?string $value): self
    {
        $this->instance->setEndAt($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Initializes a new M Break object.
     */
    public function build(): MBreak
    {
        return CoreHelper::clone($this->instance);
    }
}
