<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\Money;
use SquareConnectAPILib\Models\OrderLineItemAppliedTax;

/**
 * Builder for model OrderLineItemAppliedTax
 *
 * @see OrderLineItemAppliedTax
 */
class OrderLineItemAppliedTaxBuilder
{
    /**
     * @var OrderLineItemAppliedTax
     */
    private $instance;

    private function __construct(OrderLineItemAppliedTax $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Line Item Applied Tax Builder object.
     *
     * @param string $taxUid
     */
    public static function init(string $taxUid): self
    {
        return new self(new OrderLineItemAppliedTax($taxUid));
    }

    /**
     * Sets applied money field.
     *
     * @param Money|null $value
     */
    public function appliedMoney(?Money $value): self
    {
        $this->instance->setAppliedMoney($value);
        return $this;
    }

    /**
     * Sets uid field.
     *
     * @param string|null $value
     */
    public function uid(?string $value): self
    {
        $this->instance->setUid($value);
        return $this;
    }

    /**
     * Initializes a new Order Line Item Applied Tax object.
     */
    public function build(): OrderLineItemAppliedTax
    {
        return CoreHelper::clone($this->instance);
    }
}
