<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\Money;
use SquareConnectAPILib\Models\OrderRoundingAdjustment;

/**
 * Builder for model OrderRoundingAdjustment
 *
 * @see OrderRoundingAdjustment
 */
class OrderRoundingAdjustmentBuilder
{
    /**
     * @var OrderRoundingAdjustment
     */
    private $instance;

    private function __construct(OrderRoundingAdjustment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Rounding Adjustment Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderRoundingAdjustment());
    }

    /**
     * Sets amount money field.
     *
     * @param Money|null $value
     */
    public function amountMoney(?Money $value): self
    {
        $this->instance->setAmountMoney($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets uid field.
     *
     * @param string|null $value
     */
    public function uid(?string $value): self
    {
        $this->instance->setUid($value);
        return $this;
    }

    /**
     * Initializes a new Order Rounding Adjustment object.
     */
    public function build(): OrderRoundingAdjustment
    {
        return CoreHelper::clone($this->instance);
    }
}
