<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\RenewTokenRequest;

/**
 * Builder for model RenewTokenRequest
 *
 * @see RenewTokenRequest
 */
class RenewTokenRequestBuilder
{
    /**
     * @var RenewTokenRequest
     */
    private $instance;

    private function __construct(RenewTokenRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Renew Token Request Builder object.
     */
    public static function init(): self
    {
        return new self(new RenewTokenRequest());
    }

    /**
     * Sets access token field.
     *
     * @param string|null $value
     */
    public function accessToken(?string $value): self
    {
        $this->instance->setAccessToken($value);
        return $this;
    }

    /**
     * Initializes a new Renew Token Request object.
     */
    public function build(): RenewTokenRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
