<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\Error;
use SquareConnectAPILib\Models\ResumeSubscriptionResponse;
use SquareConnectAPILib\Models\Subscription;

/**
 * Builder for model ResumeSubscriptionResponse
 *
 * @see ResumeSubscriptionResponse
 */
class ResumeSubscriptionResponseBuilder
{
    /**
     * @var ResumeSubscriptionResponse
     */
    private $instance;

    private function __construct(ResumeSubscriptionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Resume Subscription Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ResumeSubscriptionResponse());
    }

    /**
     * Sets errors field.
     *
     * @param Error[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Sets subscription field.
     *
     * @param Subscription|null $value
     */
    public function subscription(?Subscription $value): self
    {
        $this->instance->setSubscription($value);
        return $this;
    }

    /**
     * Initializes a new Resume Subscription Response object.
     */
    public function build(): ResumeSubscriptionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
