<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\SearchSubscriptionsFilter;

/**
 * Builder for model SearchSubscriptionsFilter
 *
 * @see SearchSubscriptionsFilter
 */
class SearchSubscriptionsFilterBuilder
{
    /**
     * @var SearchSubscriptionsFilter
     */
    private $instance;

    private function __construct(SearchSubscriptionsFilter $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Search Subscriptions Filter Builder object.
     */
    public static function init(): self
    {
        return new self(new SearchSubscriptionsFilter());
    }

    /**
     * Sets customer ids field.
     *
     * @param string[]|null $value
     */
    public function customerIds(?array $value): self
    {
        $this->instance->setCustomerIds($value);
        return $this;
    }

    /**
     * Sets location ids field.
     *
     * @param string[]|null $value
     */
    public function locationIds(?array $value): self
    {
        $this->instance->setLocationIds($value);
        return $this;
    }

    /**
     * Initializes a new Search Subscriptions Filter object.
     */
    public function build(): SearchSubscriptionsFilter
    {
        return CoreHelper::clone($this->instance);
    }
}
