<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\MeasurementUnit;
use SquareConnectAPILib\Models\StandardUnitDescription;

/**
 * Builder for model StandardUnitDescription
 *
 * @see StandardUnitDescription
 */
class StandardUnitDescriptionBuilder
{
    /**
     * @var StandardUnitDescription
     */
    private $instance;

    private function __construct(StandardUnitDescription $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Standard Unit Description Builder object.
     */
    public static function init(): self
    {
        return new self(new StandardUnitDescription());
    }

    /**
     * Sets abbreviation field.
     *
     * @param string|null $value
     */
    public function abbreviation(?string $value): self
    {
        $this->instance->setAbbreviation($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets unit field.
     *
     * @param MeasurementUnit|null $value
     */
    public function unit(?MeasurementUnit $value): self
    {
        $this->instance->setUnit($value);
        return $this;
    }

    /**
     * Initializes a new Standard Unit Description object.
     */
    public function build(): StandardUnitDescription
    {
        return CoreHelper::clone($this->instance);
    }
}
