<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\SubscriptionEvent;

/**
 * Builder for model SubscriptionEvent
 *
 * @see SubscriptionEvent
 */
class SubscriptionEventBuilder
{
    /**
     * @var SubscriptionEvent
     */
    private $instance;

    private function __construct(SubscriptionEvent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Subscription Event Builder object.
     *
     * @param string $effectiveDate
     * @param string $id
     * @param string $planId
     * @param string $subscriptionEventType
     */
    public static function init(string $effectiveDate, string $id, string $planId, string $subscriptionEventType): self
    {
        return new self(new SubscriptionEvent($effectiveDate, $id, $planId, $subscriptionEventType));
    }

    /**
     * Sets info field.
     *
     * @param array|null $value
     */
    public function info(?array $value): self
    {
        $this->instance->setInfo($value);
        return $this;
    }

    /**
     * Initializes a new Subscription Event object.
     */
    public function build(): SubscriptionEvent
    {
        return CoreHelper::clone($this->instance);
    }
}
