<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\V1CreateEmployeeRoleRequest;
use SquareConnectAPILib\Models\V1EmployeeRole;

/**
 * Builder for model V1CreateEmployeeRoleRequest
 *
 * @see V1CreateEmployeeRoleRequest
 */
class V1CreateEmployeeRoleRequestBuilder
{
    /**
     * @var V1CreateEmployeeRoleRequest
     */
    private $instance;

    private function __construct(V1CreateEmployeeRoleRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V1 Create Employee Role Request Builder object.
     */
    public static function init(): self
    {
        return new self(new V1CreateEmployeeRoleRequest());
    }

    /**
     * Sets employee role field.
     *
     * @param V1EmployeeRole|null $value
     */
    public function employeeRole(?V1EmployeeRole $value): self
    {
        $this->instance->setEmployeeRole($value);
        return $this;
    }

    /**
     * Initializes a new V1 Create Employee Role Request object.
     */
    public function build(): V1CreateEmployeeRoleRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
