<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\V1PaymentItemDetail;

/**
 * Builder for model V1PaymentItemDetail
 *
 * @see V1PaymentItemDetail
 */
class V1PaymentItemDetailBuilder
{
    /**
     * @var V1PaymentItemDetail
     */
    private $instance;

    private function __construct(V1PaymentItemDetail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V1 Payment Item Detail Builder object.
     */
    public static function init(): self
    {
        return new self(new V1PaymentItemDetail());
    }

    /**
     * Sets category name field.
     *
     * @param string|null $value
     */
    public function categoryName(?string $value): self
    {
        $this->instance->setCategoryName($value);
        return $this;
    }

    /**
     * Sets item id field.
     *
     * @param string|null $value
     */
    public function itemId(?string $value): self
    {
        $this->instance->setItemId($value);
        return $this;
    }

    /**
     * Sets item variation id field.
     *
     * @param string|null $value
     */
    public function itemVariationId(?string $value): self
    {
        $this->instance->setItemVariationId($value);
        return $this;
    }

    /**
     * Sets sku field.
     *
     * @param string|null $value
     */
    public function sku(?string $value): self
    {
        $this->instance->setSku($value);
        return $this;
    }

    /**
     * Initializes a new V1 Payment Item Detail object.
     */
    public function build(): V1PaymentItemDetail
    {
        return CoreHelper::clone($this->instance);
    }
}
