<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\V1Money;
use SquareConnectAPILib\Models\V1PaymentModifier;

/**
 * Builder for model V1PaymentModifier
 *
 * @see V1PaymentModifier
 */
class V1PaymentModifierBuilder
{
    /**
     * @var V1PaymentModifier
     */
    private $instance;

    private function __construct(V1PaymentModifier $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V1 Payment Modifier Builder object.
     */
    public static function init(): self
    {
        return new self(new V1PaymentModifier());
    }

    /**
     * Sets applied money field.
     *
     * @param V1Money|null $value
     */
    public function appliedMoney(?V1Money $value): self
    {
        $this->instance->setAppliedMoney($value);
        return $this;
    }

    /**
     * Sets modifier option id field.
     *
     * @param string|null $value
     */
    public function modifierOptionId(?string $value): self
    {
        $this->instance->setModifierOptionId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new V1 Payment Modifier object.
     */
    public function build(): V1PaymentModifier
    {
        return CoreHelper::clone($this->instance);
    }
}
