<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SquareConnectAPILib\Models\V1Money;
use SquareConnectAPILib\Models\V1PaymentSurcharge;
use SquareConnectAPILib\Models\V1PaymentTax;

/**
 * Builder for model V1PaymentSurcharge
 *
 * @see V1PaymentSurcharge
 */
class V1PaymentSurchargeBuilder
{
    /**
     * @var V1PaymentSurcharge
     */
    private $instance;

    private function __construct(V1PaymentSurcharge $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V1 Payment Surcharge Builder object.
     */
    public static function init(): self
    {
        return new self(new V1PaymentSurcharge());
    }

    /**
     * Sets amount money field.
     *
     * @param V1Money|null $value
     */
    public function amountMoney(?V1Money $value): self
    {
        $this->instance->setAmountMoney($value);
        return $this;
    }

    /**
     * Sets applied money field.
     *
     * @param V1Money|null $value
     */
    public function appliedMoney(?V1Money $value): self
    {
        $this->instance->setAppliedMoney($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets rate field.
     *
     * @param string|null $value
     */
    public function rate(?string $value): self
    {
        $this->instance->setRate($value);
        return $this;
    }

    /**
     * Sets surcharge id field.
     *
     * @param string|null $value
     */
    public function surchargeId(?string $value): self
    {
        $this->instance->setSurchargeId($value);
        return $this;
    }

    /**
     * Sets taxable field.
     *
     * @param bool|null $value
     */
    public function taxable(?bool $value): self
    {
        $this->instance->setTaxable($value);
        return $this;
    }

    /**
     * Sets taxes field.
     *
     * @param V1PaymentTax[]|null $value
     */
    public function taxes(?array $value): self
    {
        $this->instance->setTaxes($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new V1 Payment Surcharge object.
     */
    public function build(): V1PaymentSurcharge
    {
        return CoreHelper::clone($this->instance);
    }
}
