<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

/**
 * Represents a bank account. For more information about
 * linking a bank account to a Square account, see
 * [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
 */
class BankAccount implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountNumberSuffix;

    /**
     * @var string
     */
    private $accountType;

    /**
     * @var string|null
     */
    private $bankName;

    /**
     * @var string
     */
    private $country;

    /**
     * @var bool
     */
    private $creditable;

    /**
     * @var string
     */
    private $currency;

    /**
     * @var string|null
     */
    private $debitMandateReferenceId;

    /**
     * @var bool
     */
    private $debitable;

    /**
     * @var string|null
     */
    private $fingerprint;

    /**
     * @var string
     */
    private $holderName;

    /**
     * @var string
     */
    private $id;

    /**
     * @var string|null
     */
    private $locationId;

    /**
     * @var string
     */
    private $primaryBankIdentificationNumber;

    /**
     * @var string|null
     */
    private $referenceId;

    /**
     * @var string|null
     */
    private $secondaryBankIdentificationNumber;

    /**
     * @var string
     */
    private $status;

    /**
     * @var int|null
     */
    private $version;

    /**
     * @param string $accountNumberSuffix
     * @param string $accountType
     * @param string $country
     * @param bool $creditable
     * @param string $currency
     * @param bool $debitable
     * @param string $holderName
     * @param string $id
     * @param string $primaryBankIdentificationNumber
     * @param string $status
     */
    public function __construct(
        string $accountNumberSuffix,
        string $accountType,
        string $country,
        bool $creditable,
        string $currency,
        bool $debitable,
        string $holderName,
        string $id,
        string $primaryBankIdentificationNumber,
        string $status
    ) {
        $this->accountNumberSuffix = $accountNumberSuffix;
        $this->accountType = $accountType;
        $this->country = $country;
        $this->creditable = $creditable;
        $this->currency = $currency;
        $this->debitable = $debitable;
        $this->holderName = $holderName;
        $this->id = $id;
        $this->primaryBankIdentificationNumber = $primaryBankIdentificationNumber;
        $this->status = $status;
    }

    /**
     * Returns Account Number Suffix.
     * The last few digits of the account number.
     */
    public function getAccountNumberSuffix(): string
    {
        return $this->accountNumberSuffix;
    }

    /**
     * Sets Account Number Suffix.
     * The last few digits of the account number.
     *
     * @required
     * @maps account_number_suffix
     */
    public function setAccountNumberSuffix(string $accountNumberSuffix): void
    {
        $this->accountNumberSuffix = $accountNumberSuffix;
    }

    /**
     * Returns Account Type.
     * The financial purpose of the associated bank account.
     */
    public function getAccountType(): string
    {
        return $this->accountType;
    }

    /**
     * Sets Account Type.
     * The financial purpose of the associated bank account.
     *
     * @required
     * @maps account_type
     */
    public function setAccountType(string $accountType): void
    {
        $this->accountType = $accountType;
    }

    /**
     * Returns Bank Name.
     * Read only. Name of actual financial institution.
     * For example "Bank of America".
     */
    public function getBankName(): ?string
    {
        return $this->bankName;
    }

    /**
     * Sets Bank Name.
     * Read only. Name of actual financial institution.
     * For example "Bank of America".
     *
     * @maps bank_name
     */
    public function setBankName(?string $bankName): void
    {
        $this->bankName = $bankName;
    }

    /**
     * Returns Country.
     * The ISO 3166 Alpha-2 country code where the bank account is based.
     */
    public function getCountry(): string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * The ISO 3166 Alpha-2 country code where the bank account is based.
     *
     * @required
     * @maps country
     */
    public function setCountry(string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Creditable.
     * Indicates whether it is possible for Square to send money to this bank account.
     */
    public function getCreditable(): bool
    {
        return $this->creditable;
    }

    /**
     * Sets Creditable.
     * Indicates whether it is possible for Square to send money to this bank account.
     *
     * @required
     * @maps creditable
     */
    public function setCreditable(bool $creditable): void
    {
        $this->creditable = $creditable;
    }

    /**
     * Returns Currency.
     * The 3-character ISO 4217 currency code indicating the operating
     * currency of the bank account. For example, the currency code for US dollars
     * is `USD`.
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     * The 3-character ISO 4217 currency code indicating the operating
     * currency of the bank account. For example, the currency code for US dollars
     * is `USD`.
     *
     * @required
     * @maps currency
     */
    public function setCurrency(string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Debit Mandate Reference Id.
     * Reference identifier that will be displayed to UK bank account owners
     * when collecting direct debit authorization. Only required for UK bank accounts.
     */
    public function getDebitMandateReferenceId(): ?string
    {
        return $this->debitMandateReferenceId;
    }

    /**
     * Sets Debit Mandate Reference Id.
     * Reference identifier that will be displayed to UK bank account owners
     * when collecting direct debit authorization. Only required for UK bank accounts.
     *
     * @maps debit_mandate_reference_id
     */
    public function setDebitMandateReferenceId(?string $debitMandateReferenceId): void
    {
        $this->debitMandateReferenceId = $debitMandateReferenceId;
    }

    /**
     * Returns Debitable.
     * Indicates whether it is possible for Square to take money from this
     * bank account.
     */
    public function getDebitable(): bool
    {
        return $this->debitable;
    }

    /**
     * Sets Debitable.
     * Indicates whether it is possible for Square to take money from this
     * bank account.
     *
     * @required
     * @maps debitable
     */
    public function setDebitable(bool $debitable): void
    {
        $this->debitable = $debitable;
    }

    /**
     * Returns Fingerprint.
     * A Square-assigned, unique identifier for the bank account based on the
     * account information. The account fingerprint can be used to compare account
     * entries and determine if the they represent the same real-world bank account.
     */
    public function getFingerprint(): ?string
    {
        return $this->fingerprint;
    }

    /**
     * Sets Fingerprint.
     * A Square-assigned, unique identifier for the bank account based on the
     * account information. The account fingerprint can be used to compare account
     * entries and determine if the they represent the same real-world bank account.
     *
     * @maps fingerprint
     */
    public function setFingerprint(?string $fingerprint): void
    {
        $this->fingerprint = $fingerprint;
    }

    /**
     * Returns Holder Name.
     * Name of the account holder. This name must match the name
     * on the targeted bank account record.
     */
    public function getHolderName(): string
    {
        return $this->holderName;
    }

    /**
     * Sets Holder Name.
     * Name of the account holder. This name must match the name
     * on the targeted bank account record.
     *
     * @required
     * @maps holder_name
     */
    public function setHolderName(string $holderName): void
    {
        $this->holderName = $holderName;
    }

    /**
     * Returns Id.
     * The unique, Square-issued identifier for the bank account.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The unique, Square-issued identifier for the bank account.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Location Id.
     * The location to which the bank account belongs.
     */
    public function getLocationId(): ?string
    {
        return $this->locationId;
    }

    /**
     * Sets Location Id.
     * The location to which the bank account belongs.
     *
     * @maps location_id
     */
    public function setLocationId(?string $locationId): void
    {
        $this->locationId = $locationId;
    }

    /**
     * Returns Primary Bank Identification Number.
     * Primary identifier for the bank. For more information, see
     * [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
     */
    public function getPrimaryBankIdentificationNumber(): string
    {
        return $this->primaryBankIdentificationNumber;
    }

    /**
     * Sets Primary Bank Identification Number.
     * Primary identifier for the bank. For more information, see
     * [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
     *
     * @required
     * @maps primary_bank_identification_number
     */
    public function setPrimaryBankIdentificationNumber(string $primaryBankIdentificationNumber): void
    {
        $this->primaryBankIdentificationNumber = $primaryBankIdentificationNumber;
    }

    /**
     * Returns Reference Id.
     * Client-provided identifier for linking the banking account to an entity
     * in a third-party system (for example, a bank account number or a user identifier).
     */
    public function getReferenceId(): ?string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     * Client-provided identifier for linking the banking account to an entity
     * in a third-party system (for example, a bank account number or a user identifier).
     *
     * @maps reference_id
     */
    public function setReferenceId(?string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Returns Secondary Bank Identification Number.
     * Secondary identifier for the bank. For more information, see
     * [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
     */
    public function getSecondaryBankIdentificationNumber(): ?string
    {
        return $this->secondaryBankIdentificationNumber;
    }

    /**
     * Sets Secondary Bank Identification Number.
     * Secondary identifier for the bank. For more information, see
     * [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
     *
     * @maps secondary_bank_identification_number
     */
    public function setSecondaryBankIdentificationNumber(?string $secondaryBankIdentificationNumber): void
    {
        $this->secondaryBankIdentificationNumber = $secondaryBankIdentificationNumber;
    }

    /**
     * Returns Status.
     * Read-only. The current verification status of this BankAccount object.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Read-only. The current verification status of this BankAccount object.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Version.
     * The current version of the `BankAccount`.
     */
    public function getVersion(): ?int
    {
        return $this->version;
    }

    /**
     * Sets Version.
     * The current version of the `BankAccount`.
     *
     * @maps version
     */
    public function setVersion(?int $version): void
    {
        $this->version = $version;
    }

    /**
     * Converts the BankAccount object to a human-readable string representation.
     *
     * @return string The string representation of the BankAccount object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BankAccount',
            [
                'accountNumberSuffix' => $this->accountNumberSuffix,
                'accountType' => $this->accountType,
                'bankName' => $this->bankName,
                'country' => $this->country,
                'creditable' => $this->creditable,
                'currency' => $this->currency,
                'debitMandateReferenceId' => $this->debitMandateReferenceId,
                'debitable' => $this->debitable,
                'fingerprint' => $this->fingerprint,
                'holderName' => $this->holderName,
                'id' => $this->id,
                'locationId' => $this->locationId,
                'primaryBankIdentificationNumber' => $this->primaryBankIdentificationNumber,
                'referenceId' => $this->referenceId,
                'secondaryBankIdentificationNumber' => $this->secondaryBankIdentificationNumber,
                'status' => $this->status,
                'version' => $this->version
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['account_number_suffix']                    = $this->accountNumberSuffix;
        $json['account_type']                             = $this->accountType;
        if (isset($this->bankName)) {
            $json['bank_name']                            = $this->bankName;
        }
        $json['country']                                  = $this->country;
        $json['creditable']                               = $this->creditable;
        $json['currency']                                 = $this->currency;
        if (isset($this->debitMandateReferenceId)) {
            $json['debit_mandate_reference_id']           = $this->debitMandateReferenceId;
        }
        $json['debitable']                                = $this->debitable;
        if (isset($this->fingerprint)) {
            $json['fingerprint']                          = $this->fingerprint;
        }
        $json['holder_name']                              = $this->holderName;
        $json['id']                                       = $this->id;
        if (isset($this->locationId)) {
            $json['location_id']                          = $this->locationId;
        }
        $json['primary_bank_identification_number']       = $this->primaryBankIdentificationNumber;
        if (isset($this->referenceId)) {
            $json['reference_id']                         = $this->referenceId;
        }
        if (isset($this->secondaryBankIdentificationNumber)) {
            $json['secondary_bank_identification_number'] = $this->secondaryBankIdentificationNumber;
        }
        $json['status']                                   = $this->status;
        if (isset($this->version)) {
            $json['version']                              = $this->version;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
