<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

class BatchDeleteCatalogObjectsRequest implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $objectIds;

    /**
     * Returns Object Ids.
     * The IDs of the CatalogObjects to be deleted. When an object is deleted, other objects
     * in the graph that depend on that object will be deleted as well (for example, deleting a
     * CatalogItem will delete its CatalogItemVariation.
     *
     * @return string[]|null
     */
    public function getObjectIds(): ?array
    {
        return $this->objectIds;
    }

    /**
     * Sets Object Ids.
     * The IDs of the CatalogObjects to be deleted. When an object is deleted, other objects
     * in the graph that depend on that object will be deleted as well (for example, deleting a
     * CatalogItem will delete its CatalogItemVariation.
     *
     * @maps object_ids
     *
     * @param string[]|null $objectIds
     */
    public function setObjectIds(?array $objectIds): void
    {
        $this->objectIds = $objectIds;
    }

    /**
     * Converts the BatchDeleteCatalogObjectsRequest object to a human-readable string representation.
     *
     * @return string The string representation of the BatchDeleteCatalogObjectsRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('BatchDeleteCatalogObjectsRequest', ['objectIds' => $this->objectIds]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->objectIds)) {
            $json['object_ids'] = $this->objectIds;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
