<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

/**
 * A batch of catalog objects.
 */
class CatalogObjectBatch implements \JsonSerializable
{
    /**
     * @var CatalogObject[]
     */
    private $objects;

    /**
     * @param CatalogObject[] $objects
     */
    public function __construct(array $objects)
    {
        $this->objects = $objects;
    }

    /**
     * Returns Objects.
     * A list of CatalogObjects belonging to this batch.
     *
     * @return CatalogObject[]
     */
    public function getObjects(): array
    {
        return $this->objects;
    }

    /**
     * Sets Objects.
     * A list of CatalogObjects belonging to this batch.
     *
     * @required
     * @maps objects
     *
     * @param CatalogObject[] $objects
     */
    public function setObjects(array $objects): void
    {
        $this->objects = $objects;
    }

    /**
     * Converts the CatalogObjectBatch object to a human-readable string representation.
     *
     * @return string The string representation of the CatalogObjectBatch object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('CatalogObjectBatch', ['objects' => $this->objects]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['objects'] = $this->objects;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
