<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

/**
 * Defines the parameters for a `CreateDisputeEvidenceText` request.
 */
class CreateDisputeEvidenceTextRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $evidenceText;

    /**
     * @var string|null
     */
    private $evidenceType;

    /**
     * @var string
     */
    private $idempotencyKey;

    /**
     * @param string $evidenceText
     * @param string $idempotencyKey
     */
    public function __construct(string $evidenceText, string $idempotencyKey)
    {
        $this->evidenceText = $evidenceText;
        $this->idempotencyKey = $idempotencyKey;
    }

    /**
     * Returns Evidence Text.
     * The evidence string.
     */
    public function getEvidenceText(): string
    {
        return $this->evidenceText;
    }

    /**
     * Sets Evidence Text.
     * The evidence string.
     *
     * @required
     * @maps evidence_text
     */
    public function setEvidenceText(string $evidenceText): void
    {
        $this->evidenceText = $evidenceText;
    }

    /**
     * Returns Evidence Type.
     * The type of evidence you are uploading.
     */
    public function getEvidenceType(): ?string
    {
        return $this->evidenceType;
    }

    /**
     * Sets Evidence Type.
     * The type of evidence you are uploading.
     *
     * @maps evidence_type
     */
    public function setEvidenceType(?string $evidenceType): void
    {
        $this->evidenceType = $evidenceType;
    }

    /**
     * Returns Idempotency Key.
     * The Unique ID. For more information, see [Idempotency](https://developer.squareup.com/docs/working-
     * with-apis/idempotency).
     */
    public function getIdempotencyKey(): string
    {
        return $this->idempotencyKey;
    }

    /**
     * Sets Idempotency Key.
     * The Unique ID. For more information, see [Idempotency](https://developer.squareup.com/docs/working-
     * with-apis/idempotency).
     *
     * @required
     * @maps idempotency_key
     */
    public function setIdempotencyKey(string $idempotencyKey): void
    {
        $this->idempotencyKey = $idempotencyKey;
    }

    /**
     * Converts the CreateDisputeEvidenceTextRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreateDisputeEvidenceTextRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateDisputeEvidenceTextRequest',
            [
                'evidenceText' => $this->evidenceText,
                'evidenceType' => $this->evidenceType,
                'idempotencyKey' => $this->idempotencyKey
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['evidence_text']     = $this->evidenceText;
        if (isset($this->evidenceType)) {
            $json['evidence_type'] = $this->evidenceType;
        }
        $json['idempotency_key']   = $this->idempotencyKey;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
