<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

/**
 * Describes a `DeleteInvoice` request.
 */
class DeleteInvoiceRequest implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $version;

    /**
     * Returns Version.
     * The version of the [invoice](https://developer.squareup.com/reference/square_2021-08-
     * 18/objects/Invoice) to delete.
     * If you do not know the version, you can call [GetInvoice](https://developer.squareup.
     * com/reference/square_2021-08-18/invoices-api/get-invoice) or
     * [ListInvoices](https://developer.squareup.com/reference/square_2021-08-18/invoices-api/list-
     * invoices).
     */
    public function getVersion(): ?int
    {
        return $this->version;
    }

    /**
     * Sets Version.
     * The version of the [invoice](https://developer.squareup.com/reference/square_2021-08-
     * 18/objects/Invoice) to delete.
     * If you do not know the version, you can call [GetInvoice](https://developer.squareup.
     * com/reference/square_2021-08-18/invoices-api/get-invoice) or
     * [ListInvoices](https://developer.squareup.com/reference/square_2021-08-18/invoices-api/list-
     * invoices).
     *
     * @maps version
     */
    public function setVersion(?int $version): void
    {
        $this->version = $version;
    }

    /**
     * Converts the DeleteInvoiceRequest object to a human-readable string representation.
     *
     * @return string The string representation of the DeleteInvoiceRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('DeleteInvoiceRequest', ['version' => $this->version]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->version)) {
            $json['version'] = $this->version;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
