<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

class DisputeEvidenceCreatedWebhookData implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var DisputeEvidenceCreatedWebhookObject|null
     */
    private $object;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns Id.
     * ID of the affected dispute.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * ID of the affected dispute.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Object.
     */
    public function getObject(): ?DisputeEvidenceCreatedWebhookObject
    {
        return $this->object;
    }

    /**
     * Sets Object.
     *
     * @maps object
     */
    public function setObject(?DisputeEvidenceCreatedWebhookObject $object): void
    {
        $this->object = $object;
    }

    /**
     * Returns Type.
     * Name of the affected dispute's type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Name of the affected dispute's type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the DisputeEvidenceCreatedWebhookData object to a human-readable string representation.
     *
     * @return string The string representation of the DisputeEvidenceCreatedWebhookData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DisputeEvidenceCreatedWebhookData',
            ['id' => $this->id, 'object' => $this->object, 'type' => $this->type]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']     = $this->id;
        }
        if (isset($this->object)) {
            $json['object'] = $this->object;
        }
        if (isset($this->type)) {
            $json['type']   = $this->type;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
