<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

/**
 * Represents a Square gift card.
 */
class GiftCard implements \JsonSerializable
{
    /**
     * @var Money|null
     */
    private $balanceMoney;

    /**
     * @var string|null
     */
    private $createdAt;

    /**
     * @var string[]|null
     */
    private $customerIds;

    /**
     * @var string|null
     */
    private $gan;

    /**
     * @var array|null
     */
    private $ganSource;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var array|null
     */
    private $state;

    /**
     * @var array
     */
    private $type;

    /**
     * @param array $type
     */
    public function __construct(array $type)
    {
        $this->type = $type;
    }

    /**
     * Returns Balance Money.
     * Represents an amount of money. `Money` fields can be signed or unsigned.
     * Fields that do not explicitly define whether they are signed or unsigned are
     * considered unsigned and can only hold positive amounts. For signed fields, the
     * sign of the value indicates the purpose of the money transfer. See
     * [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-
     * monetary-amounts)
     * for more information.
     */
    public function getBalanceMoney(): ?Money
    {
        return $this->balanceMoney;
    }

    /**
     * Sets Balance Money.
     * Represents an amount of money. `Money` fields can be signed or unsigned.
     * Fields that do not explicitly define whether they are signed or unsigned are
     * considered unsigned and can only hold positive amounts. For signed fields, the
     * sign of the value indicates the purpose of the money transfer. See
     * [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-
     * monetary-amounts)
     * for more information.
     *
     * @maps balance_money
     */
    public function setBalanceMoney(?Money $balanceMoney): void
    {
        $this->balanceMoney = $balanceMoney;
    }

    /**
     * Returns Created At.
     * The timestamp when the gift card was created, in RFC 3339 format.
     * In the case of a digital gift card, it is the time when you create a card
     * (using the Square Point of Sale application, Seller Dashboard, or Gift Cards API).
     * In the case of a plastic gift card, it is the time when Square associates the card with the
     * seller at the time of activation.
     */
    public function getCreatedAt(): ?string
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     * The timestamp when the gift card was created, in RFC 3339 format.
     * In the case of a digital gift card, it is the time when you create a card
     * (using the Square Point of Sale application, Seller Dashboard, or Gift Cards API).
     * In the case of a plastic gift card, it is the time when Square associates the card with the
     * seller at the time of activation.
     *
     * @maps created_at
     */
    public function setCreatedAt(?string $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Customer Ids.
     * The IDs of the customers to whom this gift card is linked.
     *
     * @return string[]|null
     */
    public function getCustomerIds(): ?array
    {
        return $this->customerIds;
    }

    /**
     * Sets Customer Ids.
     * The IDs of the customers to whom this gift card is linked.
     *
     * @maps customer_ids
     *
     * @param string[]|null $customerIds
     */
    public function setCustomerIds(?array $customerIds): void
    {
        $this->customerIds = $customerIds;
    }

    /**
     * Returns Gan.
     * The gift card account number.
     */
    public function getGan(): ?string
    {
        return $this->gan;
    }

    /**
     * Sets Gan.
     * The gift card account number.
     *
     * @maps gan
     */
    public function setGan(?string $gan): void
    {
        $this->gan = $gan;
    }

    /**
     * Returns Gan Source.
     */
    public function getGanSource(): ?array
    {
        return $this->ganSource;
    }

    /**
     * Sets Gan Source.
     *
     * @maps gan_source
     */
    public function setGanSource(?array $ganSource): void
    {
        $this->ganSource = $ganSource;
    }

    /**
     * Returns Id.
     * The Square-assigned ID of the gift card.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The Square-assigned ID of the gift card.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns State.
     */
    public function getState(): ?array
    {
        return $this->state;
    }

    /**
     * Sets State.
     *
     * @maps state
     */
    public function setState(?array $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Type.
     */
    public function getType(): array
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @required
     * @maps type
     */
    public function setType(array $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the GiftCard object to a human-readable string representation.
     *
     * @return string The string representation of the GiftCard object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GiftCard',
            [
                'balanceMoney' => $this->balanceMoney,
                'createdAt' => $this->createdAt,
                'customerIds' => $this->customerIds,
                'gan' => $this->gan,
                'ganSource' => $this->ganSource,
                'id' => $this->id,
                'state' => $this->state,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->balanceMoney)) {
            $json['balance_money'] = $this->balanceMoney;
        }
        if (isset($this->createdAt)) {
            $json['created_at']    = $this->createdAt;
        }
        if (isset($this->customerIds)) {
            $json['customer_ids']  = $this->customerIds;
        }
        if (isset($this->gan)) {
            $json['gan']           = $this->gan;
        }
        if (isset($this->ganSource)) {
            $json['gan_source']    = $this->ganSource;
        }
        if (isset($this->id)) {
            $json['id']            = $this->id;
        }
        if (isset($this->state)) {
            $json['state']         = $this->state;
        }
        $json['type']              = $this->type;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
