<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

/**
 * A request to list gift cards. You can optionally specify a filter to retrieve a subset of
 * gift cards.
 */
class ListGiftCardsRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cursor;

    /**
     * @var string|null
     */
    private $customerId;

    /**
     * @var int|null
     */
    private $limit;

    /**
     * @var string|null
     */
    private $state;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns Cursor.
     * A pagination cursor returned by a previous call to this endpoint.
     * Provide this cursor to retrieve the next set of results for the original query.
     * If a cursor is not provided, it returns the first page of the results.
     * For more information, see [Pagination](https://developer.squareup.com/docs/docs/working-with-
     * apis/pagination).
     */
    public function getCursor(): ?string
    {
        return $this->cursor;
    }

    /**
     * Sets Cursor.
     * A pagination cursor returned by a previous call to this endpoint.
     * Provide this cursor to retrieve the next set of results for the original query.
     * If a cursor is not provided, it returns the first page of the results.
     * For more information, see [Pagination](https://developer.squareup.com/docs/docs/working-with-
     * apis/pagination).
     *
     * @maps cursor
     */
    public function setCursor(?string $cursor): void
    {
        $this->cursor = $cursor;
    }

    /**
     * Returns Customer Id.
     * If a value is provided, returns only the gift cards linked to the specified customer
     */
    public function getCustomerId(): ?string
    {
        return $this->customerId;
    }

    /**
     * Sets Customer Id.
     * If a value is provided, returns only the gift cards linked to the specified customer
     *
     * @maps customer_id
     */
    public function setCustomerId(?string $customerId): void
    {
        $this->customerId = $customerId;
    }

    /**
     * Returns Limit.
     * If a value is provided, it returns only that number of results per page.
     * The maximum number of results allowed per page is 50. The default value is 30.
     */
    public function getLimit(): ?int
    {
        return $this->limit;
    }

    /**
     * Sets Limit.
     * If a value is provided, it returns only that number of results per page.
     * The maximum number of results allowed per page is 50. The default value is 30.
     *
     * @maps limit
     */
    public function setLimit(?int $limit): void
    {
        $this->limit = $limit;
    }

    /**
     * Returns State.
     * If the state is provided, it returns the gift cards in the specified state
     * (see [GiftCardStatus](https://developer.squareup.com/reference/square_2021-08-
     * 18/enums/GiftCardStatus)).
     * Otherwise, it returns the gift cards of all states.
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Sets State.
     * If the state is provided, it returns the gift cards in the specified state
     * (see [GiftCardStatus](https://developer.squareup.com/reference/square_2021-08-
     * 18/enums/GiftCardStatus)).
     * Otherwise, it returns the gift cards of all states.
     *
     * @maps state
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Type.
     * If a type is provided, gift cards of this type are returned
     * (see [GiftCardType](https://developer.squareup.com/reference/square_2021-08-18/enums/GiftCardType)).
     * If no type is provided, it returns gift cards of all types.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * If a type is provided, gift cards of this type are returned
     * (see [GiftCardType](https://developer.squareup.com/reference/square_2021-08-18/enums/GiftCardType)).
     * If no type is provided, it returns gift cards of all types.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the ListGiftCardsRequest object to a human-readable string representation.
     *
     * @return string The string representation of the ListGiftCardsRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListGiftCardsRequest',
            [
                'cursor' => $this->cursor,
                'customerId' => $this->customerId,
                'limit' => $this->limit,
                'state' => $this->state,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cursor)) {
            $json['cursor']      = $this->cursor;
        }
        if (isset($this->customerId)) {
            $json['customer_id'] = $this->customerId;
        }
        if (isset($this->limit)) {
            $json['limit']       = $this->limit;
        }
        if (isset($this->state)) {
            $json['state']       = $this->state;
        }
        if (isset($this->type)) {
            $json['type']        = $this->type;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
