<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

class RetrieveInventoryPhysicalCountResponse implements \JsonSerializable
{
    /**
     * @var InventoryPhysicalCount|null
     */
    private $count;

    /**
     * @var Error[]|null
     */
    private $errors;

    /**
     * Returns Count.
     * Represents the quantity of an item variation that is physically present
     * at a specific location, verified by a seller or a seller's employee. For example,
     * a physical count might come from an employee counting the item variations on
     * hand or from syncing with an external system.
     */
    public function getCount(): ?InventoryPhysicalCount
    {
        return $this->count;
    }

    /**
     * Sets Count.
     * Represents the quantity of an item variation that is physically present
     * at a specific location, verified by a seller or a seller's employee. For example,
     * a physical count might come from an employee counting the item variations on
     * hand or from syncing with an external system.
     *
     * @maps count
     */
    public function setCount(?InventoryPhysicalCount $count): void
    {
        $this->count = $count;
    }

    /**
     * Returns Errors.
     * Any errors that occurred during the request.
     *
     * @return Error[]|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     * Any errors that occurred during the request.
     *
     * @maps errors
     *
     * @param Error[]|null $errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }

    /**
     * Converts the RetrieveInventoryPhysicalCountResponse object to a human-readable string representation.
     *
     * @return string The string representation of the RetrieveInventoryPhysicalCountResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RetrieveInventoryPhysicalCountResponse',
            ['count' => $this->count, 'errors' => $this->errors]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->count)) {
            $json['count']  = $this->count;
        }
        if (isset($this->errors)) {
            $json['errors'] = $this->errors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
