<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

/**
 * A response that includes loyalty accounts that satisfy the search criteria.
 */
class SearchLoyaltyAccountsResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cursor;

    /**
     * @var Error[]|null
     */
    private $errors;

    /**
     * @var LoyaltyAccount[]|null
     */
    private $loyaltyAccounts;

    /**
     * Returns Cursor.
     * The pagination cursor to use in a subsequent
     * request. If empty, this is the final response.
     * For more information,
     * see [Pagination](https://developer.squareup.com/docs/basics/api101/pagination).
     */
    public function getCursor(): ?string
    {
        return $this->cursor;
    }

    /**
     * Sets Cursor.
     * The pagination cursor to use in a subsequent
     * request. If empty, this is the final response.
     * For more information,
     * see [Pagination](https://developer.squareup.com/docs/basics/api101/pagination).
     *
     * @maps cursor
     */
    public function setCursor(?string $cursor): void
    {
        $this->cursor = $cursor;
    }

    /**
     * Returns Errors.
     * Any errors that occurred during the request.
     *
     * @return Error[]|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     * Any errors that occurred during the request.
     *
     * @maps errors
     *
     * @param Error[]|null $errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }

    /**
     * Returns Loyalty Accounts.
     * The loyalty accounts that met the search criteria,
     * in order of creation date.
     *
     * @return LoyaltyAccount[]|null
     */
    public function getLoyaltyAccounts(): ?array
    {
        return $this->loyaltyAccounts;
    }

    /**
     * Sets Loyalty Accounts.
     * The loyalty accounts that met the search criteria,
     * in order of creation date.
     *
     * @maps loyalty_accounts
     *
     * @param LoyaltyAccount[]|null $loyaltyAccounts
     */
    public function setLoyaltyAccounts(?array $loyaltyAccounts): void
    {
        $this->loyaltyAccounts = $loyaltyAccounts;
    }

    /**
     * Converts the SearchLoyaltyAccountsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the SearchLoyaltyAccountsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SearchLoyaltyAccountsResponse',
            ['cursor' => $this->cursor, 'errors' => $this->errors, 'loyaltyAccounts' => $this->loyaltyAccounts]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cursor)) {
            $json['cursor']           = $this->cursor;
        }
        if (isset($this->errors)) {
            $json['errors']           = $this->errors;
        }
        if (isset($this->loyaltyAccounts)) {
            $json['loyalty_accounts'] = $this->loyaltyAccounts;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
