<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class V1EmployeeRolePermissionsEnum
{
    public const REGISTER_ACCESS_SALES_HISTORY = 'REGISTER_ACCESS_SALES_HISTORY';

    public const REGISTER_APPLY_RESTRICTED_DISCOUNTS = 'REGISTER_APPLY_RESTRICTED_DISCOUNTS';

    public const REGISTER_CHANGE_SETTINGS = 'REGISTER_CHANGE_SETTINGS';

    public const REGISTER_EDIT_ITEM = 'REGISTER_EDIT_ITEM';

    public const REGISTER_ISSUE_REFUNDS = 'REGISTER_ISSUE_REFUNDS';

    public const REGISTER_OPEN_CASH_DRAWER_OUTSIDE_SALE = 'REGISTER_OPEN_CASH_DRAWER_OUTSIDE_SALE';

    public const REGISTER_VIEW_SUMMARY_REPORTS = 'REGISTER_VIEW_SUMMARY_REPORTS';

    private const _ALL_VALUES = [
        self::REGISTER_ACCESS_SALES_HISTORY,
        self::REGISTER_APPLY_RESTRICTED_DISCOUNTS,
        self::REGISTER_CHANGE_SETTINGS,
        self::REGISTER_EDIT_ITEM,
        self::REGISTER_ISSUE_REFUNDS,
        self::REGISTER_OPEN_CASH_DRAWER_OUTSIDE_SALE,
        self::REGISTER_VIEW_SUMMARY_REPORTS
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for V1EmployeeRolePermissionsEnum.");
    }
}
