<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use SquareConnectAPILib\ApiHelper;
use stdClass;

class V1UpdateEmployeeRequest implements \JsonSerializable
{
    /**
     * @var V1Employee
     */
    private $body;

    /**
     * @param V1Employee $body
     */
    public function __construct(V1Employee $body)
    {
        $this->body = $body;
    }

    /**
     * Returns Body.
     * Represents one of a business's employees.
     */
    public function getBody(): V1Employee
    {
        return $this->body;
    }

    /**
     * Sets Body.
     * Represents one of a business's employees.
     *
     * @required
     * @maps body
     */
    public function setBody(V1Employee $body): void
    {
        $this->body = $body;
    }

    /**
     * Converts the V1UpdateEmployeeRequest object to a human-readable string representation.
     *
     * @return string The string representation of the V1UpdateEmployeeRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('V1UpdateEmployeeRequest', ['body' => $this->body]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['body'] = $this->body;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
