<?php

declare(strict_types=1);

/*
 * SquareConnectAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SquareConnectAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The days of the week.
 */
class WeekdayEnum
{
    /**
     * Monday
     */
    public const MON = 'MON';

    /**
     * Tuesday
     */
    public const TUE = 'TUE';

    /**
     * Wednesday
     */
    public const WED = 'WED';

    /**
     * Thursday
     */
    public const THU = 'THU';

    /**
     * Friday
     */
    public const FRI = 'FRI';

    /**
     * Saturday
     */
    public const SAT = 'SAT';

    /**
     * Sunday
     */
    public const SUN = 'SUN';

    private const _ALL_VALUES = [self::MON, self::TUE, self::WED, self::THU, self::FRI, self::SAT, self::SUN];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for WeekdayEnum.");
    }
}
